import { Client, Room } from "colyseus";
import { TURN_TIMEOUT_MS, chooseBigTwoBotAction, createBigTwoGame, passTurn, playCards, resolveTurnTimeout, type BigTwoState } from "../../lib/games/big-two";
import { getBotPlayerNameForDifficulty } from "../../lib/games/core/botNames";
import type { BigTwoClientMessage, BigTwoServerEvent } from "../messages/bigTwoMessages";
import { BigTwoRoomStateSchema, syncBigTwoPublicState, type LobbyBigTwoPlayer } from "../schema/BigTwoRoomState";
import { DefaultRoomScheduler, type RoomScheduler, type ScheduledTask } from "../utilities/scheduler";

export class BigTwoRoomController {
  readonly publicState = new BigTwoRoomStateSchema(); private lobby: LobbyBigTwoPlayer[] = []; private game: BigTwoState | null = null; private botCounter = 1; private deadline = 0; private turnTask: ScheduledTask | null = null; private botTask: ScheduledTask | null = null;
  constructor(private options: { roomCode?: string; maxPlayers?: number; bots?: number; difficulty?: "easy" | "normal" | "hard"; random?: () => number; scheduler?: RoomScheduler; emit?: (event: BigTwoServerEvent, playerId?: string) => void; onStart?: () => void } = {}) { this.publicState.roomCode = options.roomCode ?? createRoomCode(options.random ?? Math.random); this.publicState.maxPlayers = options.maxPlayers === 3 ? 3 : 4; this.sync(); }
  get state() { return this.game; } private get scheduler() { return this.options.scheduler ?? (this.options.scheduler = new DefaultRoomScheduler()); } private get emit() { return this.options.emit ?? (() => undefined); }
  addHuman(sessionId: string, nickname: string, clientId?: string) { if (this.game) throw new Error("Game already started."); const existing = this.lobby.find((player) => player.sessionId === sessionId || (clientId && player.clientId === clientId)); if (existing) { existing.id = `player-${sessionId}`; existing.sessionId = sessionId; existing.clientId = clientId; existing.nickname = sanitizeNickname(nickname); existing.connected = true; this.sync(); return; } if (this.lobby.length >= this.publicState.maxPlayers) throw new Error("Room is full."); this.lobby.push({ id: `player-${sessionId}`, nickname: sanitizeNickname(nickname), seat: this.lobby.length, type: "human", sessionId, clientId, connected: true, ready: false, host: !this.lobby.some((player) => player.type === "human") }); let bots = Number(this.options.bots ?? 0); while (bots > 0 && this.lobby.length < this.publicState.maxPlayers) { this.addBotInternal(this.options.difficulty ?? "normal"); bots -= 1; } this.options.bots = 0; this.sync(); }
  setReady(sessionId: string, ready: boolean) { this.requireHuman(sessionId).ready = ready; this.sync(); }
  addBot(sessionId: string, difficulty: "easy" | "normal" | "hard") { this.requireHost(sessionId); if (this.lobby.length >= this.publicState.maxPlayers) throw new Error("Room is full."); this.addBotInternal(difficulty); this.sync(); }
  removeBot(sessionId: string, botId: string) { this.requireHost(sessionId); this.lobby = this.lobby.filter((player) => player.type !== "bot" || player.id !== botId).map((player, seat) => ({ ...player, seat })); this.sync(); }
  start(sessionId: string) { this.requireHost(sessionId); if (this.lobby.length !== this.publicState.maxPlayers) throw new Error("All seats must be filled."); if (!this.lobby.every((player) => player.type === "bot" || player.connected)) throw new Error("All players must be connected."); this.game = createBigTwoGame({ players: this.lobby.map((player) => ({ id: player.id, nickname: player.nickname, type: player.type, botDifficulty: player.botDifficulty, connected: player.connected, seat: player.seat })), random: this.options.random }); this.options.onStart?.(); this.emit({ type: "GAME_STARTED" }); this.afterAction(); }
  play(sessionId: string, actionId: string, cardIds: string[]) { const player = this.requireHuman(sessionId); if (!Array.isArray(cardIds) || cardIds.length === 0 || cardIds.length > 5 || !cardIds.every((cardId) => typeof cardId === "string" && cardId.length > 0)) throw new Error("Invalid cards payload."); this.game = playCards(this.requireGame(), player.id, cardIds, this.scheduler.now(), actionId); this.emit({ type: "CARDS_PLAYED", playerId: player.id, cards: this.game.lastPlay?.cards ?? [], combination: this.game.lastPlay?.combination.type ?? "" }); this.afterAction(); }
  pass(sessionId: string, actionId: string) { const player = this.requireHuman(sessionId); const beforeLeader = this.game?.trickLeaderId; this.game = passTurn(this.requireGame(), player.id, this.scheduler.now(), actionId); this.emit({ type: "PLAYER_PASSED", playerId: player.id }); if (!this.game.lastPlay && this.game.trickLeaderId === beforeLeader) this.emit({ type: "TRICK_RESET", leaderId: this.game.trickLeaderId ?? "" }); this.afterAction(); }
  requestHand(sessionId: string) { this.sendHand(this.requireHuman(sessionId).id); }
  reset(sessionId: string) { this.requireHost(sessionId); this.cancel(); this.game = null; this.publicState.round += 1; this.lobby = this.lobby.filter((player) => player.type === "bot" || player.connected).map((player, seat) => ({ ...player, seat, ready: player.type === "bot" })); this.sync(); }
  disconnect(sessionId: string) { const player = this.lobby.find((item) => item.sessionId === sessionId); if (player) { player.connected = false; if (!this.game) player.ready = false; } this.sync(); }
  reconnect(sessionId: string) { const player = this.lobby.find((item) => item.sessionId === sessionId); if (player) player.connected = true; this.sync(); if (player) this.sendHand(player.id); }
  dispose() { this.cancel(); }
  private afterAction() { this.cancel(); this.sync(); this.sendHands(); if (!this.game) return; if (this.game.phase === "finished") { this.emit({ type: "GAME_FINISHED", winnerIds: this.game.winnerIds, reason: this.game.winReason ?? "normal" }); return; } this.deadline = this.scheduler.now() + TURN_TIMEOUT_MS; this.sync(); this.emit({ type: "TURN_CHANGED", playerId: this.game.currentPlayerId ?? "", deadline: this.deadline }); this.turnTask = this.scheduler.setTimeout(() => { if (!this.game) return; this.game = resolveTurnTimeout(this.game, this.scheduler.now()); this.afterAction(); }, TURN_TIMEOUT_MS); const current = this.lobby.find((player) => player.id === this.game?.currentPlayerId); if (current?.type === "bot") this.botTask = this.scheduler.setTimeout(() => { if (!this.game || this.game.currentPlayerId !== current.id) return; const action = chooseBigTwoBotAction(this.game, current.id, current.botDifficulty, this.options.random); const actionId = `bot-${current.id}-${this.game.turnNumber}`; this.game = action?.type === "PASS" ? passTurn(this.game, current.id, this.scheduler.now(), actionId) : action?.type === "PLAY_CARDS" ? playCards(this.game, current.id, action.cardIds, this.scheduler.now(), actionId) : this.game; this.afterAction(); }, 650); }
  private sync() { syncBigTwoPublicState(this.publicState, this.game, this.lobby, this.deadline); }
  private sendHands() { this.lobby.filter((player) => player.type === "human").forEach((player) => this.sendHand(player.id)); }
  private sendHand(playerId: string) { if (!this.game) return; this.emit({ type: "PRIVATE_HAND", cards: this.game.hands[playerId] ?? [], bonusCard: this.game.bonusCardRecipientId === playerId }, playerId); }
  private addBotInternal(difficulty: "easy" | "normal" | "hard") { this.lobby.push({ id: `bot-${this.botCounter}`, nickname: getBotPlayerNameForDifficulty(this.botCounter, difficulty, this.options.random ?? Math.random, this.lobby.map((player) => player.nickname)), seat: this.lobby.length, type: "bot", botDifficulty: difficulty, connected: true, ready: true, host: false }); this.botCounter += 1; }
  private requireGame() { if (!this.game) throw new Error("Game is not started."); return this.game; }
  private requireHuman(sessionId: string) { const player = this.lobby.find((item) => item.sessionId === sessionId); if (!player) throw new Error("Unknown player."); return player; }
  private requireHost(sessionId: string) { const player = this.requireHuman(sessionId); if (!player.host) throw new Error("Only the host can do this."); return player; }
  private cancel() { this.scheduler.clear(this.turnTask); this.scheduler.clear(this.botTask); this.turnTask = null; this.botTask = null; }
}

export class BigTwoRoom extends Room { private controller!: BigTwoRoomController; private closing = false;
  onCreate(options: { maxPlayers?: number; bots?: number; difficulty?: "easy" | "normal" | "hard" } = {}) { this.controller = new BigTwoRoomController({ maxPlayers: options.maxPlayers, bots: options.bots, difficulty: options.difficulty, emit: (event, playerId) => this.emitEvent(event, playerId), onStart: () => this.lock() }); const roomCode = this.controller.publicState.roomCode; this.setMetadata({ roomCode }); const listing = (this as unknown as { listing?: Record<string, unknown> }).listing; if (listing) listing.roomCode = roomCode; this.setState(this.controller.publicState); for (const type of ["SET_READY", "START_GAME", "ADD_BOT", "REMOVE_BOT", "PLAY_CARDS", "PASS", "REQUEST_STATE", "PLAY_AGAIN", "CLOSE_ROOM"]) this.onMessage(type, (client, message: BigTwoClientMessage) => this.handle(client, message)); }
  onJoin(client: Client, options: { nickname?: string; clientId?: string } = {}) { try { this.controller.addHuman(client.sessionId, options.nickname ?? "玩家", sanitizeClientId(options.clientId)); } catch (error) { client.send("big-two:event", reject(undefined, error)); client.leave(); } }
  async onLeave(client: Client, consented?: boolean) { this.controller.disconnect(client.sessionId); if (this.closing || consented) return; try { await this.allowReconnection(client, 30); this.controller.reconnect(client.sessionId); } catch { this.controller.disconnect(client.sessionId); } }
  onDispose() { this.controller.dispose(); }
  private handle(client: Client, message: BigTwoClientMessage) { try { switch (message.type) { case "SET_READY": this.controller.setReady(client.sessionId, message.ready); break; case "START_GAME": this.controller.start(client.sessionId); break; case "ADD_BOT": this.controller.addBot(client.sessionId, message.difficulty); break; case "REMOVE_BOT": this.controller.removeBot(client.sessionId, message.botId); break; case "PLAY_CARDS": this.controller.play(client.sessionId, message.actionId, message.cardIds); break; case "PASS": this.controller.pass(client.sessionId, message.actionId); break; case "REQUEST_STATE": this.controller.requestHand(client.sessionId); break; case "PLAY_AGAIN": this.unlock(); this.controller.reset(client.sessionId); break; case "CLOSE_ROOM": this.closeRoom(); break; } } catch (error) { client.send("big-two:event", reject(message.actionId, error)); } }
  private emitEvent(event: BigTwoServerEvent, playerId?: string) { if (!playerId) { this.broadcast("big-two:event", event); return; } this.clients.find((client) => `player-${client.sessionId}` === playerId)?.send("big-two:event", event); }
  private closeRoom() { if (this.closing) return; this.closing = true; this.lock(); this.broadcast("big-two:event", { type: "ROOM_CLOSED", reason: "cancelled" }); this.disconnect(); }
}
function reject(actionId: string | undefined, error: unknown): BigTwoServerEvent { return { type: "ACTION_REJECTED", actionId, reason: error instanceof Error ? error.message : "Action rejected." }; }
function createRoomCode(random: () => number) { return String(Math.floor(100000 + random() * 900000)); }
function sanitizeNickname(value: string) { return value.trim().slice(0, 16) || "玩家"; }
function sanitizeClientId(value?: string) { return value?.replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 48) || undefined; }
