import { Client, Room } from "colyseus";
import { advancePickRedPoints, choosePickRedBotAction, createPickRedPointsGame, PICK_RED_MAX_PLAYERS, PICK_RED_MIN_PLAYERS, PICK_RED_RECONNECT_WINDOW_SECONDS, PICK_RED_TURN_DURATION_MS, playPickRedHandCard, selectPickRedCaptureTarget, type BotDifficulty, type PickRedPointsState } from "../../lib/games/pick-red-points";
import { getBotPlayerNameForDifficulty } from "../../lib/games/core/botNames";
import { PickRedPointsRoomStateSchema, syncPickRedPublicState, type LobbyPickRedPlayer } from "../schema/PickRedPointsRoomState";
import type { PickRedPointsClientMessage, PickRedPointsServerEvent } from "../messages/pickRedPointsMessages";
import type { PickRedPointsAction } from "../../lib/games/pick-red-points";
import { DefaultRoomScheduler, type RoomScheduler, type ScheduledTask } from "../utilities/scheduler";

type Options = { roomCode?: string; maxPlayers?: number; bots?: number; difficulty?: string; scheduler?: RoomScheduler; random?: () => number; emit?: (event: PickRedPointsServerEvent, playerId?: string) => void; onGameStarted?: () => void };

export class PickRedPointsRoomController {
  readonly publicState = new PickRedPointsRoomStateSchema();
  private readonly scheduler: RoomScheduler; private readonly random: () => number; private readonly emit: (event: PickRedPointsServerEvent, playerId?: string) => void; private readonly onGameStarted: () => void;
  private lobbyPlayers: LobbyPickRedPlayer[] = []; private gameState: PickRedPointsState | null = null; private actions = new Set<string>(); private turnTask: ScheduledTask | null = null; private targetTask: ScheduledTask | null = null; private botTask: ScheduledTask | null = null; private botCounter = 1; private turnToken = 0; private botCount: number; private difficulty: BotDifficulty;
  constructor(options: Options = {}) { this.scheduler = options.scheduler ?? new DefaultRoomScheduler(); this.random = options.random ?? Math.random; this.emit = options.emit ?? (() => undefined); this.onGameStarted = options.onGameStarted ?? (() => undefined); this.publicState.roomCode = options.roomCode ?? String(Math.floor(100000 + this.random() * 900000)); this.publicState.maxPlayers = Math.max(PICK_RED_MIN_PLAYERS, Math.min(PICK_RED_MAX_PLAYERS, Math.floor(options.maxPlayers ?? 4))); this.botCount = Math.max(0, Math.floor(options.bots ?? 0)); this.difficulty = parseDifficulty(options.difficulty); this.sync(); }
  get state() { return this.gameState; }
  addHuman(sessionId: string, nickname: string, clientId?: string) { if (this.gameState) throw new Error("ROOM_LOCKED"); const existing = this.lobbyPlayers.find((player) => player.sessionId === sessionId || (clientId && player.clientId === clientId)); if (existing) { existing.sessionId = sessionId; existing.clientId = clientId ?? existing.clientId; existing.connected = true; existing.nickname = sanitizeNickname(nickname); this.sync(); return; } if (this.lobbyPlayers.length >= this.publicState.maxPlayers) throw new Error("PLAYER_LIMIT_REACHED"); this.lobbyPlayers.push({ id: `player-${sessionId}`, nickname: sanitizeNickname(nickname), seat: this.lobbyPlayers.length, type: "human", sessionId, clientId, connected: true, ready: false, host: !this.lobbyPlayers.some((player) => player.type === "human") }); while (this.botCount > 0 && this.lobbyPlayers.length < this.publicState.maxPlayers) { this.addBotInternal(this.difficulty); this.botCount -= 1; } this.sync(); }
  markDisconnected(sessionId: string) { const player = this.lobbyPlayers.find((item) => item.sessionId === sessionId); if (player) { player.connected = false; if (!this.gameState) player.ready = false; } this.promoteHost(); this.sync(); }
  markReconnected(sessionId: string) { const player = this.lobbyPlayers.find((item) => item.sessionId === sessionId); if (player) player.connected = true; this.sync(); }
  setReady(sessionId: string, actionId: string, ready: boolean) { this.fresh(actionId); if (this.gameState) throw new Error("ROOM_LOCKED"); const player = this.human(sessionId); player.ready = ready; this.sync(); }
  addBot(sessionId: string, actionId: string, difficulty: BotDifficulty) { this.fresh(actionId); this.host(sessionId); if (this.gameState) throw new Error("ROOM_LOCKED"); if (this.lobbyPlayers.length >= this.publicState.maxPlayers) throw new Error("PLAYER_LIMIT_REACHED"); this.addBotInternal(difficulty); this.sync(); }
  startGame(sessionId: string, actionId: string) { this.fresh(actionId); this.host(sessionId); if (this.lobbyPlayers.length < PICK_RED_MIN_PLAYERS) throw new Error("Pick red points needs at least 2 players."); if (!this.lobbyPlayers.every((player) => player.type === "bot" || (player.connected && player.ready))) throw new Error("All joined players must be ready."); this.gameState = createPickRedPointsGame({ players: this.lobbyPlayers.map((player) => ({ id: player.id, nickname: player.nickname, type: player.type, botDifficulty: player.botDifficulty as BotDifficulty | undefined, connected: player.connected })), random: this.random }); this.onGameStarted(); this.emit({ type: "GAME_STARTED" }); this.startTurn(); }
  playHand(sessionId: string, actionId: string, cardId: string) { this.fresh(actionId); const player = this.human(sessionId); this.apply(player.id, { type: "PLAY_HAND_CARD", actionId, cardId }); }
  selectTarget(sessionId: string, actionId: string, targetCardId: string, pendingSource: "hand" | "draw") { this.fresh(actionId); const player = this.human(sessionId); this.apply(player.id, { type: "SELECT_CAPTURE_TARGET", actionId, targetCardId, pendingSource }); }
  processDue(token = this.turnToken) { if (!this.gameState || token !== this.turnToken) return; const state = this.gameState; if (state.phase === "selecting-hand-target" || state.phase === "selecting-draw-target") { this.gameState = advancePickRedPoints(state, this.scheduler.now()); this.afterState(); return; } const player = this.lobbyPlayers.find((item) => item.id === state.currentPlayerId); if (!player) return; this.gameState = choosePickRedBotAction(state, player.id, player.botDifficulty as BotDifficulty | undefined ?? "normal", this.scheduler.now()); this.afterState(); }
  close() { this.cancel(); }
  dispose() { this.cancel(); }
  private apply(playerId: string, action: PickRedPointsAction) { if (!this.gameState) throw new Error("INVALID_PHASE"); this.gameState = action.type === "PLAY_HAND_CARD" ? playPickRedHandCard(this.gameState, playerId, action.cardId, this.scheduler.now(), action.actionId) : selectPickRedCaptureTarget(this.gameState, playerId, action.targetCardId, action.pendingSource, this.scheduler.now(), action.actionId); this.afterState(); }
  private afterState() { this.sync(); this.sendHands(); this.emit({ type: "STATE_EVENT", message: this.gameState?.lastResult ?? "" }); if (this.gameState?.phase === "finished") this.emit({ type: "GAME_FINISHED", winners: this.gameState.winners }); else this.drive(); }
  private drive() { if (!this.gameState) return; if (this.gameState.phase === "drawing") { this.gameState = requireDraw(this.gameState, this.scheduler.now()); this.afterState(); return; } if (this.gameState.phase === "selecting-hand-target" || this.gameState.phase === "selecting-draw-target") { this.cancelTarget(); const token = this.turnToken; this.targetTask = this.scheduler.setTimeout(() => this.processDue(token), Math.max(0, (this.gameState?.targetDeadline ?? this.scheduler.now()) - this.scheduler.now())); const player = this.lobbyPlayers.find((item) => item.id === this.gameState?.currentPlayerId); if (player?.type === "bot") this.botTask = this.scheduler.setTimeout(() => { if (this.gameState) { this.gameState = choosePickRedBotAction(this.gameState, player.id, player.botDifficulty as BotDifficulty | undefined, this.scheduler.now()); this.afterState(); } }, 650); return; } this.startTurn(); }
  private startTurn() { this.cancelTurn(); if (!this.gameState || this.gameState.phase === "finished") { this.sync(); return; } this.turnToken += 1; const token = this.turnToken; this.publicState.turnDeadline = this.scheduler.now() + PICK_RED_TURN_DURATION_MS; this.sync(); this.sendHands(); this.turnTask = this.scheduler.setTimeout(() => this.processDue(token), PICK_RED_TURN_DURATION_MS); const player = this.lobbyPlayers.find((item) => item.id === this.gameState?.currentPlayerId); if (player?.type === "bot") this.botTask = this.scheduler.setTimeout(() => this.processDue(token), 700); }
  private sendHands() { this.lobbyPlayers.filter((player) => player.type === "human").forEach((player) => { if (this.gameState) this.emit({ type: "HAND_UPDATED", cards: this.gameState.hands[player.id] ?? [] }, player.id); }); }
  private sync() { syncPickRedPublicState(this.publicState, this.gameState, this.lobbyPlayers, this.publicState.turnDeadline); }
  private addBotInternal(difficulty: BotDifficulty) { const number = this.botCounter++; const id = `bot-${number}`; this.lobbyPlayers.push({ id, nickname: getBotPlayerNameForDifficulty(number, difficulty, this.random, this.lobbyPlayers.map((player) => player.nickname)), seat: this.lobbyPlayers.length, type: "bot", botDifficulty: difficulty, connected: true, ready: true, host: false }); }
  private human(sessionId: string) { const player = this.lobbyPlayers.find((item) => item.sessionId === sessionId && item.type === "human"); if (!player) throw new Error("Unknown player."); return player; }
  private host(sessionId: string) { const player = this.human(sessionId); if (!player.host) throw new Error("Only the host can do this."); return player; }
  private fresh(actionId: string) { if (!actionId || this.actions.has(actionId)) throw new Error("ACTION_ALREADY_PROCESSED"); this.actions.add(actionId); }
  private promoteHost() { if (this.lobbyPlayers.some((player) => player.host && player.connected)) return; const next = this.lobbyPlayers.find((player) => player.type === "human" && player.connected); this.lobbyPlayers = this.lobbyPlayers.map((player) => ({ ...player, host: player.id === next?.id })); }
  private cancelTurn() { this.scheduler.clear(this.turnTask); this.scheduler.clear(this.botTask); this.turnTask = null; this.botTask = null; }
  private cancelTarget() { this.scheduler.clear(this.targetTask); this.targetTask = null; }
  private cancel() { this.cancelTurn(); this.cancelTarget(); }
}

function requireDraw(state: PickRedPointsState, now: number) { return advancePickRedPoints(state, now); }

export class PickRedPointsRoom extends Room {
  private controller!: PickRedPointsRoomController; private closing = false;
  onCreate(options: { maxPlayers?: number; bots?: number; difficulty?: string } = {}) { this.controller = new PickRedPointsRoomController({ maxPlayers: options.maxPlayers, bots: Number(options.bots ?? 0), difficulty: options.difficulty, emit: (event, playerId) => this.emitEvent(event, playerId), onGameStarted: () => this.lock() }); this.setMetadata({ roomCode: this.controller.publicState.roomCode }); const listing = (this as unknown as { listing?: Record<string, unknown> }).listing; if (listing) listing.roomCode = this.controller.publicState.roomCode; this.setState(this.controller.publicState); ["SET_READY", "START_GAME", "ADD_BOT", "PLAY_HAND_CARD", "SELECT_CAPTURE_TARGET", "CLOSE_ROOM"].forEach((type) => this.onMessage(type, (client, message) => this.handleMessage(client, message as PickRedPointsClientMessage))); }
  onJoin(client: Client, options: { nickname?: string; clientId?: string } = {}) { try { this.controller.addHuman(client.sessionId, options.nickname ?? "玩家", sanitizeClientId(options.clientId)); } catch (error) { client.send("pick-red-points:event", reject(undefined, error)); client.leave(); } }
  async onLeave(client: Client, consented?: boolean) { this.controller.markDisconnected(client.sessionId); if (this.closing || consented) return; try { await this.allowReconnection(client, PICK_RED_RECONNECT_WINDOW_SECONDS); this.controller.markReconnected(client.sessionId); } catch { this.controller.markDisconnected(client.sessionId); } }
  onDispose() { this.controller.dispose(); }
  private handleMessage(client: Client, message: PickRedPointsClientMessage) { try { switch (message.type) { case "SET_READY": this.controller.setReady(client.sessionId, message.actionId, message.ready); break; case "START_GAME": this.controller.startGame(client.sessionId, message.actionId); break; case "ADD_BOT": this.controller.addBot(client.sessionId, message.actionId, message.difficulty); break; case "PLAY_HAND_CARD": this.controller.playHand(client.sessionId, message.actionId, message.cardId); break; case "SELECT_CAPTURE_TARGET": this.controller.selectTarget(client.sessionId, message.actionId, message.targetCardId, message.pendingSource); break; case "CLOSE_ROOM": this.closeRoom(); break; } } catch (error) { client.send("pick-red-points:event", reject(message.actionId, error)); } }
  private emitEvent(event: PickRedPointsServerEvent, playerId?: string) { if (!playerId) this.broadcast("pick-red-points:event", event); else this.clients.find((client) => `player-${client.sessionId}` === playerId)?.send("pick-red-points:event", event); }
  private closeRoom() { if (this.closing) return; this.closing = true; this.controller.close(); this.lock(); this.broadcast("pick-red-points:event", { type: "ROOM_CLOSED", reason: "left" }); this.disconnect(); }
}

function reject(actionId: string | undefined, error: unknown): PickRedPointsServerEvent { return { type: "ACTION_REJECTED", actionId, reason: error instanceof Error ? error.message : "Action rejected." }; }
function sanitizeNickname(value: string) { return value.trim().slice(0, 16) || "玩家"; }
function sanitizeClientId(value: string | undefined) { const clean = value?.replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 48); return clean || undefined; }
function parseDifficulty(value?: string): BotDifficulty { return value === "簡單" || value === "easy" ? "easy" : value === "困難" || value === "hard" ? "hard" : "normal"; }
