import { ArraySchema, Schema, defineTypes } from "@colyseus/schema";
import type { BigTwoState } from "../../lib/games/big-two";

export class PublicBigTwoPlayer extends Schema { id = ""; nickname = ""; seat = 0; type = "human"; status = "waiting"; connected = true; ready = false; cardsRemaining = 0; botDifficulty = ""; host = false; passed = false; }
defineTypes(PublicBigTwoPlayer, { id: "string", nickname: "string", seat: "number", type: "string", status: "string", connected: "boolean", ready: "boolean", cardsRemaining: "number", botDifficulty: "string", host: "boolean", passed: "boolean" });
export class PublicBigTwoCard extends Schema { id = ""; rank = ""; suit = ""; }
defineTypes(PublicBigTwoCard, { id: "string", rank: "string", suit: "string" });
export class BigTwoRoomStateSchema extends Schema { roomCode = ""; phase = "waiting"; maxPlayers = 4; round = 1; currentPlayerId = ""; trickLeaderId = ""; turnDeadline = 0; turnNumber = 0; firstTurnPending = true; lastPlayerId = ""; lastCombination = ""; notice = ""; winReason = ""; players = new ArraySchema<PublicBigTwoPlayer>(); lastCards = new ArraySchema<PublicBigTwoCard>(); winnerIds = new ArraySchema<string>(); }
defineTypes(BigTwoRoomStateSchema, { roomCode: "string", phase: "string", maxPlayers: "number", round: "number", currentPlayerId: "string", trickLeaderId: "string", turnDeadline: "number", turnNumber: "number", firstTurnPending: "boolean", lastPlayerId: "string", lastCombination: "string", notice: "string", winReason: "string", players: [PublicBigTwoPlayer], lastCards: [PublicBigTwoCard], winnerIds: ["string"] });

export type LobbyBigTwoPlayer = { id: string; nickname: string; seat: number; type: "human" | "bot"; botDifficulty?: "easy" | "normal" | "hard"; sessionId?: string; clientId?: string; connected: boolean; ready: boolean; host: boolean };
export function syncBigTwoPublicState(schema: BigTwoRoomStateSchema, state: BigTwoState | null, lobby: LobbyBigTwoPlayer[], deadline = 0) {
  schema.phase = state?.phase ?? "waiting"; schema.currentPlayerId = state?.currentPlayerId ?? ""; schema.trickLeaderId = state?.trickLeaderId ?? ""; schema.turnDeadline = deadline; schema.turnNumber = state?.turnNumber ?? 0; schema.firstTurnPending = state?.firstTurnPending ?? true; schema.lastPlayerId = state?.lastPlay?.playerId ?? ""; schema.lastCombination = state?.lastPlay?.combination.type ?? ""; schema.notice = createNotice(state, lobby); schema.winReason = state?.winReason ?? "";
  schema.lastCards.clear(); state?.lastPlay?.cards.forEach((card) => { const next = new PublicBigTwoCard(); next.id = card.id; next.rank = card.rank; next.suit = card.suit; schema.lastCards.push(next); });
  schema.winnerIds.clear(); state?.winnerIds.forEach((id) => schema.winnerIds.push(id)); schema.players.clear();
  const players = state ? state.players.map((player) => { const source = lobby.find((item) => item.id === player.id); return { ...player, ready: true, host: Boolean(source?.host), connected: player.type === "bot" || Boolean(source?.connected), cardsRemaining: state.hands[player.id]?.length ?? 0 }; }) : lobby.map((player) => ({ ...player, status: "waiting", cardsRemaining: 0, passed: false }));
  players.sort((a, b) => a.seat - b.seat).forEach((player) => { const next = new PublicBigTwoPlayer(); next.id = player.id; next.nickname = player.nickname; next.seat = player.seat; next.type = player.type; next.status = player.status; next.connected = player.connected; next.ready = player.type === "bot" || player.ready; next.cardsRemaining = player.cardsRemaining; next.botDifficulty = player.botDifficulty ?? ""; next.host = player.host; next.passed = state?.passedPlayerIds.includes(player.id) ?? false; schema.players.push(next); });
}
function createNotice(state: BigTwoState | null, lobby: LobbyBigTwoPlayer[]) { if (!state) return "等待玩家準備"; if (state.phase === "finished") return state.winReason === "thirteen-rank-dragon" ? "一條龍！直接勝利" : "本局結束"; if (!state.lastPlay) return state.firstTurnPending ? "第一手必須包含梅花 3" : "新墩，可以自由出牌"; const name = lobby.find((player) => player.id === state.lastPlay?.playerId)?.nickname ?? "玩家"; return `${name} 出了${combinationLabel(state.lastPlay.combination.type)}`; }
function combinationLabel(value: string) { return ({ single: "單張", pair: "對子", straight: "順子", "full-house": "葫蘆", "four-of-a-kind": "鐵支", "straight-flush": "同花順" } as Record<string, string>)[value] ?? value; }

