import { createStandardDeck, type Card, type Rank, type Suit } from "../core/cards";
import { BIG_TWO_RANK_ORDER, BIG_TWO_STRAIGHTS, BIG_TWO_SUIT_ORDER } from "./constants";
import { BigTwoRuleError, type BigTwoCombination, type BigTwoPlayer, type BigTwoState } from "./types";

export function rankValue(rank: Rank) { return BIG_TWO_RANK_ORDER.indexOf(rank); }
export function suitValue(suit: Suit) { return BIG_TWO_SUIT_ORDER.indexOf(suit); }
export function cardValue(card: Card) { return rankValue(card.rank) * 4 + suitValue(card.suit); }
export function sortBigTwoCards(cards: Card[]) { return [...cards].sort((a, b) => cardValue(a) - cardValue(b)); }
export function ensureThreeOfClubsIsDealt(deck: Card[], playerCount: 3 | 4) { const next = [...deck]; if (playerCount === 3 && next.at(-1)?.id === "clubs-3") [next[next.length - 2], next[next.length - 1]] = [next[next.length - 1], next[next.length - 2]]; return next; }
export function dealBigTwoCards(deck: Card[], playerIds: string[]) { const playerCount = playerIds.length as 3 | 4; const prepared = ensureThreeOfClubsIsDealt(deck, playerCount); const dealCount = playerCount === 3 ? 51 : 52; const hands = Object.fromEntries(playerIds.map((id) => [id, [] as Card[]])); for (let index = 0; index < dealCount; index += 1) hands[playerIds[index % playerCount]].push(prepared[index]); const threeHolder = playerIds.find((id) => hands[id].some((card) => card.id === "clubs-3")); let bonusCardRecipientId: string | null = null; if (playerCount === 3 && threeHolder) { hands[threeHolder].push(prepared[51]); bonusCardRecipientId = threeHolder; } for (const id of playerIds) hands[id] = sortBigTwoCards(hands[id]); return { hands, bonusCardRecipientId }; }
export function isThirteenRankDragon(hand: Card[]) { return hand.length === 13 && new Set(hand.map((card) => card.rank)).size === 13; }
export function findDragonWinners(hands: Record<string, Card[]>, playerCount: 3 | 4) { return playerCount === 4 ? Object.keys(hands).filter((id) => isThirteenRankDragon(hands[id])) : []; }

export function classifyCombination(cards: Card[]): BigTwoCombination | null {
  const sorted = sortBigTwoCards(cards);
  if (sorted.length === 1) return { type: "single", size: 1, isBomb: false, categoryRank: 0, comparisonKey: [cardValue(sorted[0])] };
  if (sorted.length === 2) { if (sorted[0].rank !== sorted[1].rank) return null; return { type: "pair", size: 2, isBomb: false, categoryRank: 0, comparisonKey: [rankValue(sorted[0].rank), Math.max(...sorted.map((card) => suitValue(card.suit)))] }; }
  if (sorted.length !== 5) return null;
  const groups = groupRanks(sorted); const rankSet = [...new Set(sorted.map((card) => card.rank))]; const straightIndex = BIG_TWO_STRAIGHTS.findIndex((sequence) => sequence.every((rank) => rankSet.includes(rank as Rank)) && rankSet.length === 5); const flush = sorted.every((card) => card.suit === sorted[0].suit);
  if (straightIndex >= 0) { const highRank = BIG_TWO_STRAIGHTS[straightIndex][3] === "2" ? "2" : BIG_TWO_STRAIGHTS[straightIndex][4]; const highSuit = Math.max(...sorted.filter((card) => card.rank === highRank).map((card) => suitValue(card.suit))); return { type: flush ? "straight-flush" : "straight", size: 5, isBomb: flush, categoryRank: flush ? 2 : 0, comparisonKey: [straightIndex, highSuit] }; }
  const triple = [...groups.entries()].find(([, list]) => list.length === 3); const pair = [...groups.entries()].find(([, list]) => list.length === 2); if (triple && pair) return { type: "full-house", size: 5, isBomb: false, categoryRank: 0, comparisonKey: [rankValue(triple[0])] };
  const four = [...groups.entries()].find(([, list]) => list.length === 4); if (four) return { type: "four-of-a-kind", size: 5, isBomb: true, categoryRank: 1, comparisonKey: [rankValue(four[0])] };
  return null;
}

export function compareCombinations(candidate: BigTwoCombination, previous: BigTwoCombination) { if (candidate.isBomb || previous.isBomb) { if (!candidate.isBomb) return -1; if (!previous.isBomb) return 1; if (candidate.categoryRank !== previous.categoryRank) return candidate.categoryRank - previous.categoryRank; } else if (candidate.type !== previous.type || candidate.size !== previous.size) return Number.NEGATIVE_INFINITY; for (let index = 0; index < Math.max(candidate.comparisonKey.length, previous.comparisonKey.length); index += 1) { const delta = (candidate.comparisonKey[index] ?? 0) - (previous.comparisonKey[index] ?? 0); if (delta) return delta; } return 0; }

export function createBigTwoGame({ players, random = Math.random }: { players: Array<Omit<BigTwoPlayer, "seat" | "status" | "plays" | "passes"> & { seat?: number }>; random?: () => number }): BigTwoState {
  if (players.length !== 3 && players.length !== 4) throw new Error("Big Two requires 3 or 4 players.");
  const deck = shuffle(createStandardDeck(), random); const { hands, bonusCardRecipientId } = dealBigTwoCards(deck, players.map((player) => player.id)); const normalized = players.map((player, seat) => ({ ...player, seat: player.seat ?? seat, status: "playing" as const, plays: 0, passes: 0 })); const dragonWinners = findDragonWinners(hands, players.length); const openingRevealCards: Record<string, Card[]> = {}; if (dragonWinners.length) for (const id of dragonWinners) { openingRevealCards[id] = [...hands[id]]; hands[id] = []; } const starter = normalized.find((player) => hands[player.id].some((card) => card.id === "clubs-3"))?.id ?? null;
  return { phase: dragonWinners.length ? "finished" : "playing", playerCount: players.length, players: normalized.map((player) => dragonWinners.includes(player.id) ? { ...player, status: "winner" } : player), hands, bonusCardRecipientId, openingRevealCards, currentPlayerId: dragonWinners.length ? null : starter, trickLeaderId: starter, lastPlay: null, playHistory: [], passedPlayerIds: [], firstTurnPending: true, turnNumber: 1, winnerIds: dragonWinners, winReason: dragonWinners.length ? "thirteen-rank-dragon" : null, actionIds: [] };
}

export function playCards(state: BigTwoState, playerId: string, cardIds: string[], now: number, actionId: string) { assertAction(state, playerId, actionId); if (![1, 2, 5].includes(cardIds.length)) throw new BigTwoRuleError("INVALID_CARD_COUNT"); if (new Set(cardIds).size !== cardIds.length) throw new BigTwoRuleError("DUPLICATE_CARD_ID"); const hand = state.hands[playerId] ?? []; const cards = cardIds.map((id) => hand.find((card) => card.id === id)); if (cards.some((card) => !card)) throw new BigTwoRuleError("CARD_NOT_OWNED"); const owned = cards as Card[]; const combination = classifyCombination(owned); if (!combination) throw new BigTwoRuleError("INVALID_COMBINATION"); if (state.firstTurnPending && !cardIds.includes("clubs-3")) throw new BigTwoRuleError("MUST_INCLUDE_THREE_OF_CLUBS"); if (state.lastPlay) { const comparison = compareCombinations(combination, state.lastPlay.combination); if (comparison === Number.NEGATIVE_INFINITY) throw new BigTwoRuleError("MUST_MATCH_CARD_COUNT"); if (comparison <= 0) throw new BigTwoRuleError("PLAY_NOT_HIGH_ENOUGH"); } const next = cloneState(state); next.actionIds.push(actionId); next.hands[playerId] = hand.filter((card) => !cardIds.includes(card.id)); next.players = next.players.map((player) => player.id === playerId ? { ...player, plays: player.plays + 1 } : player); next.turnNumber += 1; const play = { id: actionId, playerId, cards: sortBigTwoCards(owned), combination, playedAt: now, turnNumber: state.turnNumber }; next.lastPlay = play; next.playHistory.push(play); next.trickLeaderId = playerId; next.firstTurnPending = false; if (next.hands[playerId].length === 0) { next.phase = "finished"; next.currentPlayerId = null; next.winnerIds = [playerId]; next.winReason = "normal"; next.players = next.players.map((player) => player.id === playerId ? { ...player, status: "winner" } : player); return next; } next.currentPlayerId = getNextActivePlayer(next, playerId); return next; }
export function passTurn(state: BigTwoState, playerId: string, _now: number, actionId: string) { assertAction(state, playerId, actionId); if (!state.lastPlay) throw new BigTwoRuleError("CANNOT_PASS_ON_LEAD"); const next = cloneState(state); next.actionIds.push(actionId); next.passedPlayerIds = [...new Set([...next.passedPlayerIds, playerId])]; next.players = next.players.map((player) => player.id === playerId ? { ...player, passes: player.passes + 1 } : player); const activeOthers = next.players.filter((player) => player.status === "playing" && player.id !== next.trickLeaderId); if (activeOthers.every((player) => next.passedPlayerIds.includes(player.id))) { next.currentPlayerId = next.trickLeaderId; next.lastPlay = null; next.passedPlayerIds = []; next.turnNumber += 1; return next; } next.currentPlayerId = getNextActivePlayer(next, playerId); next.turnNumber += 1; return next; }
export function getNextActivePlayer(state: BigTwoState, fromPlayerId: string) { const ordered = [...state.players].sort((a, b) => a.seat - b.seat); const start = ordered.findIndex((player) => player.id === fromPlayerId); for (let offset = 1; offset <= ordered.length; offset += 1) { const player = ordered[(start + offset) % ordered.length]; if (player.status === "playing" && !state.passedPlayerIds.includes(player.id)) return player.id; } return state.trickLeaderId; }
export function getLegalPlays(state: BigTwoState, playerId: string) { const hand = state.hands[playerId] ?? []; const candidates = [...combinations(hand, 1), ...combinations(hand, 2), ...combinations(hand, 5)]; return candidates.filter((cards) => { const combination = classifyCombination(cards); if (!combination) return false; if (state.firstTurnPending && !cards.some((card) => card.id === "clubs-3")) return false; return !state.lastPlay || compareCombinations(combination, state.lastPlay.combination) > 0; }).sort((a, b) => a.length - b.length || cardsStrength(a) - cardsStrength(b)); }
export function resolveTurnTimeout(state: BigTwoState, now: number) { if (!state.currentPlayerId) return state; const actionId = `timeout-${state.turnNumber}-${state.currentPlayerId}`; if (state.lastPlay) return passTurn(state, state.currentPlayerId, now, actionId); const play = getLegalPlays(state, state.currentPlayerId)[0]; return playCards(state, state.currentPlayerId, play.map((card) => card.id), now, actionId); }
function assertAction(state: BigTwoState, playerId: string, actionId: string) { if (state.phase === "finished") throw new BigTwoRuleError("GAME_ALREADY_FINISHED"); if (state.phase !== "playing") throw new BigTwoRuleError("GAME_NOT_PLAYING"); if (state.actionIds.includes(actionId)) throw new BigTwoRuleError("ACTION_ALREADY_PROCESSED"); if (state.currentPlayerId !== playerId) throw new BigTwoRuleError("NOT_YOUR_TURN"); }
function groupRanks(cards: Card[]) { const groups = new Map<Rank, Card[]>(); for (const card of cards) groups.set(card.rank, [...(groups.get(card.rank) ?? []), card]); return groups; }
function cardsStrength(cards: Card[]) { return classifyCombination(cards)?.comparisonKey.reduce((sum, value, index) => sum + value * 100 ** (2 - index), 0) ?? Infinity; }
function combinations<T>(items: T[], size: number, start = 0, picked: T[] = [], result: T[][] = []): T[][] { if (picked.length === size) { result.push([...picked]); return result; } for (let index = start; index <= items.length - (size - picked.length); index += 1) { picked.push(items[index]); combinations(items, size, index + 1, picked, result); picked.pop(); } return result; }
function shuffle<T>(items: T[], random: () => number) { const next = [...items]; for (let index = next.length - 1; index > 0; index -= 1) { const swap = Math.floor(random() * (index + 1)); [next[index], next[swap]] = [next[swap], next[index]]; } return next; }
function cloneState(state: BigTwoState): BigTwoState { return { ...state, players: state.players.map((player) => ({ ...player })), hands: Object.fromEntries(Object.entries(state.hands).map(([id, hand]) => [id, [...hand]])), openingRevealCards: Object.fromEntries(Object.entries(state.openingRevealCards).map(([id, cards]) => [id, [...cards]])), lastPlay: state.lastPlay ? { ...state.lastPlay, cards: [...state.lastPlay.cards], combination: { ...state.lastPlay.combination, comparisonKey: [...state.lastPlay.combination.comparisonKey] } } : null, playHistory: [...state.playHistory], passedPlayerIds: [...state.passedPlayerIds], winnerIds: [...state.winnerIds], actionIds: [...state.actionIds] }; }

